#=================================================
# Title: Batch Trigger Build
# Description: This actions will run another workflows with delay from "$DELAY_INT" environment
# Lisence: MIT
# Author: helmiau
# Blog: https://helmiau.com
#=================================================
# Usage notes:
# - Create a GitHub (if you don't have it) and login
# - Create a new (Personal Access Token) with "read, write repo and workflow" permissions, go to https://github.com/settings/tokens/new to create new token .
# - Copy your token and keep it, because you won't see it anymore.
# - Go to https://github.com/your_username/HelmiWrt-OS-Immortal/settings/secrets/actions (change your_username with yours).
# - Create new Actions Secrets by clicking "New repository secret" with name "HELMIWRT_RW".
# - Paste your token to "Value" coloumn, then save it with green button under this coloumn.
# - Then you can run this actions.
#=================================================

name: Batch Trigger Build

on:
  workflow_dispatch:
#  schedule:
#    - cron: 0 17 * * *
#  watch:
#    types: started

env:
  REPO_OWNER: helmiau
  REPO_NAME: HelmiWrt-OS-Immortal
  BRANCH_NAME: main
  # delay interval in seconds
  DELAY_INT: 200
  # other configs
  FAILPROP: false
  TRIGGERWF: true
  WAITWF: false
  

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Checkout
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Actions Checkout running succesfully, resuming build
        run: |
          echo "BUILD_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
          sleep 15
          echo "Actions Checkout running succesfully, resuming build"

      - name: Create Release Tag for This Repository
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          name: HelmiWrt OS ${{ env.BUILD_DATE }}
          token: ${{ secrets.HELMIWRT_RW }}
          tag: helmiwrt-${{ env.BUILD_DATE }}
          body: release_body.txt

      - name: Create Release Tag for DL Repository
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          repo: dl
          name: HelmiWrt OS ${{ env.BUILD_DATE }}
          token: ${{ secrets.HELMIWRT_RW }}
          tag: helmiwrt-${{ env.BUILD_DATE }}
          body: release_body.txt

      - name: Actions Checkout running succesfully, resuming build
        run: |
          sleep 15
          echo "Actions Checkout running succesfully, resuming build"

      - name: Running Raspberry Pi 1 18.06 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi1-18.06.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Raspberry Pi 1 21.02 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi1-21.02.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Raspberry Pi 2 18.06 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi2-18.06.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Raspberry Pi 2 21.02 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi2-21.02.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Raspberry Pi 3 18.06 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi3-18.06.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Raspberry Pi 3 21.02 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi3-21.02.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Raspberry Pi 4 18.06 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi4-18.06.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Raspberry Pi 4 21.02 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi4-21.02.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Armvirt64 18.06 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-armvirt-18.06.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Armvirt64 21.02 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-armvirt-21.02.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Rockchip 18.06 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rockchip-18.06.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Rockchip 21.02 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rockchip-21.02.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Sunxi Cortexa7 18.06 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-sunxi-18.06.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Sunxi Cortexa7 21.02 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-sunxi-21.02.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running x86/64 18.06 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-x86-64-18.06.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running  x86/64 21.02 Build
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-x86-64-21.02.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"
